# Generated by Django 2.2.3 on 2019-07-09 09:08

from django.db import migrations
from api import tmdb


def populate_genres(apps, schema_editor):
    Genre = apps.get_model('api', 'Genre')
    genres = tmdb.fetch_genres()
    for genre in genres:
        Genre.objects.create(**genre)


def clear_genres(apps, schema_editor):
    Genre = apps.get_model('api', 'Genre')
    Genre.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial')
    ]

    operations = [
        migrations.RunPython(populate_genres, clear_genres)
    ]
